resources:
  repositories:
    - repository: self
      checkoutOptions:
        submodules: true
        lfs: true
trigger:
  batch: true
  branches:
    include:
      - master
      - develop
      - feature/*
      - bugfix/*
      - release/*
  paths:
    include:
      - azure-pipelines.yml
      - src/*
      - tests/*
variables:
  - group: Environment
  - group: DotNet
  - group: ApiKeys
  - name: SONAR_PROJECT
    value: akritikos_azDevOpsCI
pool:
  vmImage: ubuntu-latest
stages:
  - template: .config/ci/.azure-pipelines/stages/general/semver.yml
  - template: .config/ci/.azure-pipelines/stages/dotnet/build.yml
    parameters:
      useCache: false
  - template: .config/ci/.azure-pipelines/stages/dotnet/test.yml
    parameters:
      useCache: false
  - template: .config/ci/.azure-pipelines/stages/dotnet/deploy-nuget.yml
    parameters:
      stageName: ReleaseCI
      environment: kritikos-io
      packagesToPush: $(Pipeline.Workspace)/nuget/*.nupkg
      feedName: kritikos
