parameters:
- name: artifactType
  type: string
  default: artifact
- name: 'key'
  type: string
  default: '"$(Agent.OS)"'
- name: 'path'
  type: 'string'

steps:
- task: Cache@2
  inputs:
    key: ${{ parameters.key }}
    path: ${{ parameters.path }}
  displayName: Restore ${{ parameters.artifactType }} cache
