jobs:
- job: Version
  steps:
    - template: dotnet-tool.yml
      parameters:
        toolName: gitversion.tool
    - pwsh: ../dotnet-gitversion /output buildserver /updateassemblyinfo
      displayName: Set SemVer from git history
