parameters:
- name: coverageTool
  default: 'cobertura'
  type: string
  values:
     - cobertura
     - jacoco
- name: summaryFile
  default: '$(build.artifactStagingDirectory)/coverage/coverage.cobertura.xml'
  type: 'string'

steps:
- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: ${{ parameters.coverageTool }}
    summaryFileLocation: ${{ parameters.summaryFile }}
  displayName: Publish code coverage
