parameters:
  - name: coverageDirectory
    type: string
    default: $(build.artifactStagingDirectory)/coverage

steps:
- ${{  if ne(variables['Build.Reason'], 'PullRequest') }}:
  - pwsh: ../csmacnz.Coveralls --opencover --input "${{ parameters.coverageDirectory }}/coverage.opencover.xml" --useRelativePaths --commitId "$(Build.SourceVersion)" --commitBranch "$(Build.SourceBranchName)" --commitAuthor "$(Build.RequestedFor)" --commitEmail "$(Build.RequestedForEmail)" --commitMessage "$(Build.SourceVersionMessage)" --jobId "$(Build.BuildId)" --serviceName "dev.azure.com" --serviceNumber "$(Build.BuildId)"
    displayName: Upload coverage to Codecov (CI)
- ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
  - pwsh: ../csmacnz.Coveralls --opencover --input "${{ parameters.coverageDirectory }}/coverage.opencover.xml"1 --useRelativePaths --commitId "$(Build.SourceVersion)" --commitBranch "$(Build.SourceBranchName)" --commitAuthor "$(Build.RequestedFor)" --commitEmail "$(Build.RequestedForEmail)" --commitMessage "$(Build.SourceVersionMessage)" --jobId "$(Build.BuildId)" --serviceName "dev.azure.com" --serviceNumber "$(Build.BuildId)" --pullRequest "$(System.PullRequest.PullRequestId)"
    displayName: Upload coverage to Codecov (PR)
