parameters:
  - name: image
    type: string
    default: ubuntu-latest
  - name: useCache
    type: boolean
    default: true
  - name: producePackedArtifacts
    type: boolean
    default: false
  - name: sdkVersion
    default: '5.x'
    type: string
  - name: configuration
    type: string
    default: $(BuildConfiguration)
  - name: buildArgs
    type: string
    default: ''
  - name: publishWeb
    type: boolean
    default: false
  - name: outputPath
    type: string
    default: $(build.artifactStagingDirectory)/publish
  - name: pathtoPublish
    type: string
    default: $(build.artifactStagingDirectory)/publish
  - name: publishArtifactName
    type: string
    default: '$(Build.Repository.Name)-$(Build.BuildNumber)'
  - name: projectsToPack
    type: string
    default: 'src/*/*.csproj'
  - name: packDirectory
    type: string
    default: $(build.artifactStagingDirectory)/nuget
  - name: nugetArtifactName
    type: string
    default: 'nuget'


jobs:
- job: Build
  displayName: on ${{ parameters.image }}
  steps:
  - checkout: self
    fetchDepth: 1
  - ${{ if parameters.useCache }}:
    - template: ../../steps/dotnet/nuget-cache.yml
  - template: ../../steps/dotnet/install-sdk.yml
    parameters:
      sdkVersion: ${{ parameters.sdkVersion }}
  - template: ../../steps/dotnet/restore.yml
  - template: ../../steps/dotnet/build.yml
    parameters:
      configuration: ${{ parameters.configuration }}
      buildArgs: ${{ parameters.buildArgs }}
  - template: ../../steps/dotnet/publish.yml
    parameters:
      configuration: ${{ parameters.configuration }}
      publishWeb: ${{ parameters.publishWeb }}
      outputPath: ${{ parameters.outputPath }}
  - template: ../../steps/general/publish-artifact.yml
    parameters:
      pathtoPublish: ${{ parameters.pathtoPublish }}
      artifactName: ${{ parameters.publishArtifactName }}-${{ parameters.image }}
  - ${{ if parameters.producePackedArtifacts }}:
    - template: ../../steps/dotnet/pack.yml
      parameters:
        configuration: ${{ parameters.configuration }}
        projectsToPack: ${{ parameters.projectsToPack }}
        packDirectory: ${{ parameters.packDirectory }}
    - template: ../../steps/general/publish-artifact.yml
      parameters:
        pathtoPublish: ${{ parameters.packDirectory }}
        artifactName: ${{ parameters.nugetArtifactName }}
