parameters:
  - name: artifact
    type: string
    default: nuget
  - name: feedName
    type: string
    default: 'Kritikos'
  - name: environment
    type: string
    default: 'kritikos-io'

jobs:
- deployment:
  displayName: Push nugets to ${{ parameters.environment }}
  environment: ${{ parameters.environment }}
  strategy:
    runOnce:
      deploy:
        steps:
          - download: current
            artifact: ${{ parameters.artifact }}
          - template: ../../steps/dotnet/nuget-push.yml
            parameters:
              packagesToPush: $(Pipeline.Workspace)/${{ parameters.artifact }}/*.nupkg
              feedName: ${{ parameters.feedName }}
