parameters:
  - name: image
    type: string
    default: ubuntu-latest
  - name: useCache
    type: boolean
    default: true
  - name: publishCoverage
    type: boolean
    default: false
  - name: sdkVersion
    default: '5.x'
    type: string
  - name: configuration
    type: string
    default: $(BuildConfiguration)
  - name: buildArgs
    type: string
    default: ''
  - name: coverageTool
    default: cobertura
    type: string
    values:
    - cobertura
    - jacoco
  - name: summaryFile
    default: '$(build.artifactStagingDirectory)/coverage/coverage.cobertura.xml'
    type: 'string'
  - name: coverageDirectory
    type: string
    default: $(build.artifactStagingDirectory)/coverage
  - name: coverageArtifactName
    type: string
    default: $(Build.Repository.Name)-$(Build.BuildNumber)-coverage

jobs:
- job:
  displayName: on ${{ parameters.image }}
  pool:
    vmImage: ${{ parameters.image }}
  steps:
  - checkout: self
  - ${{ if parameters.useCache }}:
    - template: ../../steps/dotnet/nuget-cache.yml
  - template: ../../steps/dotnet/install-sdk.yml
    parameters:
      sdkVersion: ${{ parameters.sdkVersion }}
  - ${{ if parameters.publishCoverage }}:
    - template: ../../steps/general/cover-tools.yml
  - template: ../../steps/dotnet/restore.yml
  - ${{ if parameters.publishCoverage }}:
    - template: ../../steps/general/sonar-scanner-begin.yml
      parameters:
        coverageDirectory: ${{ parameters.publishCoverage }}
  - template: ../../steps/dotnet/build.yml
    parameters:
      configuration: ${{ parameters.configuration }}
      buildArgs: ${{ parameters.buildArgs }}
  - template: ../../steps/dotnet/test.yml
    parameters:
      configuration: ${{ parameters.configuration }}
  - ${{ if parameters.publishCoverage }}:
    - template: ../../steps/general/publish-coverage.yml
      parameters:
        summaryFile: ${{ parameters.summaryFile }}
    - template: ../../steps/general/publish-artifact.yml
      parameters:
        pathtoPublish: ${{ parameters.coverageDirectory }}
        artifactName: ${{ parameters.coverageArtifactName }}
    - template: ../../steps/general/sonar-scanner-end.yml
    - template: ../../steps/general/upload-codecov.yml
      parameters:
        coverageDirectory: ${{ parameters.coverageDirectory }}


