parameters:
- name: sdkVersion
  default: '5.x'
  type: string
- name: configuration
  type: string
  default: $(BuildConfiguration)
- name: buildArgs
  type: string
  default: ''

stages:
- stage: Build
  displayName: Builds artifacts
  dependsOn: Version
  jobs:
  - job: Build
    steps:
    - checkout: self
      fetchDepth: 1
    # - template: ../../steps/dotnet/nuget-cache.yml
    - template: ../../steps/dotnet/install-sdk.yml
      parameters:
        sdkVersion: ${{ parameters.sdkVersion }}
    - template: ../../steps/dotnet/restore.yml
    - template: ../../steps/dotnet/build.yml
      parameters:
        configuration: ${{ parameters.buildArgs }}
        buildArgs: ${{ parameters.buildArgs }}
