parameters:
  - name: sdkVersion
    default: '5.x'
    type: string

stages:
- stage: Build
  displayName: Builds artifacts
  dependsOn: Version
  jobs:
  - job: Build
    steps:
    - checkout: self
      fetchDepth: 1
    # - template: ../../steps/dotnet/nuget-cache.yml
    - template: ../../steps/dotnet/install-sdk.yml
      parameters:
        sdkVersion: ${{ parameters.sdkVersion }}
    - template: ../../steps/dotnet/restore.yml
