parameters:
  - name: sdkVersion
    default: '5.x'
    type: string
  - name: useCache
    type: boolean
    default: true
  - name: configuration
    type: string
    default: $(BuildConfiguration)
  - name: buildArgs
    type: string
    default: ''
  - name: publishWeb
    type: boolean
    default: false
  - name: outputPath
    type: string
    default: $(build.artifactStagingDirectory)/publish
  - name: pathtoPublish
    type: string
    default: $(build.artifactStagingDirectory)/publish
  - name: publishArtifactName
    type: string
    default: '$(Build.Repository.Name)-$(Build.BuildNumber)'
  - name: projectsToPack
    type: string
    default: 'src/*/*.csproj'
  - name: packDirectory
    type: string
    default: $(build.artifactStagingDirectory)/nuget
  - name: nugetArtifactName
    type: string
    default: 'nuget'


stages:
- stage: Build
  displayName: Build artifacts
  dependsOn: Version
  jobs:
    - template: ../../jobs/dotnet/build.yml
      parameters:
        image: ubuntu-latest
        producePackedArtifacts: true
        useCache: ${{ parameters.useCache }}
        sdkVersion: ${{ parameters.sdkVersion }}
        configuration: ${{ parameters.configuration }}
        buildArgs: ${{ parameters.buildArgs }}
        publishWeb: ${{ parameters.publishWeb }}
        outputPath: ${{ parameters.outputPath }}
        pathtoPublish: ${{ parameters.pathtoPublish }}
        publishArtifactName: ${{ parameters.publishArtifactName }}
        projectsToPack: ${{ parameters.projectsToPack }}
        packDirectory: ${{ parameters.packDirectory }}
        nugetArtifactName: ${{ parameters.nugetArtifactName }}

