parameters:
  - name: sdkVersion
    default: '5.x'
    type: string
  - name: configuration
    type: string
    default: $(BuildConfiguration)
  - name: buildArgs
    type: string
    default: ''
  - name: publishWeb
    type: boolean
    default: false
  - name: outputPath
    type: string
    default: $(build.artifactStagingDirectory)/publish

stages:
- stage: Build
  displayName: Builds artifacts
  dependsOn: Version
  jobs:
  - job: Build
    steps:
    - checkout: self
      fetchDepth: 1
    # - template: ../../steps/dotnet/nuget-cache.yml
    - template: ../../steps/dotnet/install-sdk.yml
      parameters:
        sdkVersion: ${{ parameters.sdkVersion }}
    - template: ../../steps/dotnet/restore.yml
    - template: ../../steps/dotnet/build.yml
      parameters:
        configuration: ${{ parameters.configuration }}
        buildArgs: ${{ parameters.buildArgs }}
    - template: ../../steps/dotnet/publish.yml
      parameters:
        configuration: ${{ parameters.configuration }}
        publishWeb: ${{ parameters.publishWeb }}
        outputPath: ${{ parameters.outputPath }}

