parameters:
  - name: stageName
    type: string
    default: Release
  - name: artifact
    type: string
    default: nuget
  - name: feedName
    type: string
    default: 'Kritikos'
  - name: environment
    type: string
    default: 'kritikos-io'

stages:
- stage: ${{ parameters.stageName }}
  displayName: on ${{ parameters.environment }}
  dependsOn:
    - Build
    - Test
  condition: succeeded()
  jobs:
    - template: ../../jobs/dotnet/deploy-nuget.yml
      parameters:
        artifact: ${{ parameters.artifact }}
        feedName: ${{ parameters.feedName }}
        environment: ${{ parameters.environment }}
