parameters:
  - name: sdkVersion
    default: '5.x'
    type: string
  - name: useCache
    type: boolean
    default: true
  - name: configuration
    type: string
    default: $(BuildConfiguration)
  - name: buildArgs
    type: string
    default: ''

stages:
- stage: Test
  displayName: Run tests
  dependsOn: Version
  jobs:
    - template: ../../jobs/dotnet/test.yml
      parameters:
        image: ubuntu-latest
        useCache: false
        publishCoverage: true
        sdkVersion: ${{ parameters.sdkVersion }}
        configuration: ${{ parameters.configuration }}
        buildArgs: ${{ parameters.buildArgs }}
    - template: ../../jobs/dotnet/test.yml
      parameters:
        image: windows-latest
        useCache: false
        publishCoverage: false
        sdkVersion: ${{ parameters.sdkVersion }}
        configuration: ${{ parameters.configuration }}
        buildArgs: ${{ parameters.buildArgs }}
    - template: ../../jobs/dotnet/test.yml
      parameters:
        image: macOS-latest
        useCache: false
        publishCoverage: false
        sdkVersion: ${{ parameters.sdkVersion }}
        configuration: ${{ parameters.configuration }}
        buildArgs: ${{ parameters.buildArgs }}
