parameters:
  - name: sdkVersion
    default: '5.x'
    type: string
  - name: configuration
    type: string
    default: $(BuildConfiguration)
  - name: buildArgs
    type: string
    default: ''

stages:
- stage: Test
  displayName: Builds artifacts
  dependsOn: Version
  jobs:
    - template: ../../jobs/dotnet/test.yml
      parameters:
        sdkVersion: ${{ parameters.sdkVersion }}
        configuration: ${{ parameters.configuration }}
        buildArgs: ${{ parameters.buildArgs }}
