parameters:
  - name: jdkVersion
    type: string
    default: 13

steps:
- task: JavaToolInstaller@0
  displayName: Install JDK ${{ parameters.jdkVersion }}
  inputs:
    versionSpec: ${{ parameters.jdkVersion }}
    jdkSourceOption: 'PreInstalled'
