parameters:
  - name: sdkVersion
    default: '5.x'
    type: string

steps:
- task: UseDotNet@2
  displayName: Install required SDK version
  inputs:
    packageType: 'sdk'
    version: ${{ parameters.sdkVersion }}
